apiVersion: v1
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>Page Title</title>
    </head>
    <body>

    <h1>{{ .Release.Name }}</h1>

    </body>
    </html>
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: default
