apiVersion: v1
kind: Service
metadata:
  name: occ-{{ .Release.Name }}-service
  labels:
    name: occ-{{ .Release.Name }}-service
  namespace: default  
spec:
  type: NodePort
  ports:
    - port: 80
      {{- if eq .Release.Name "shop" }}
      nodePort: {{ .Values.port.shop }}
      {{- else if eq .Release.Name "cart" }}
      nodePort: {{ .Values.port.cart }}
      {{- else if eq .Release.Name "payment" }}
      nodePort: {{ .Values.port.payment }}
      {{- else if eq .Release.Name "checkout" }}
      nodePort: {{ .Values.port.checkout }}    
      {{- end }}
  selector:
    app: occ-{{ .Release.Name }}